version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: defaultdb
      POSTGRES_USER: avnadmin
      POSTGRES_PASSWORD: AVNS_idP2IXcb1cML4cbbp1K

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "9000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://avnadmin:AVNS_idP2IXcb1cML4cbbp1K@pg-3cc05ec6-sayan-chat-app.g.aivencloud.com:28370/defaultdb?sslmode=require

volumes:
  postgres_data:
